### ISSUE TITLE
unused argument error

### ISSUE THREAD

**Issue by Quantitative72** [jamgreen/lehdr#13]
Code worked for me a few months ago. Using same code again and getting this: 
Error in grab_lodes(state = c("al", "ak", "az",   : unused argument (tract = TRUE)
Any ideas what is causing the error?

**Comment by jamgreen** [comment]
hmmm...can you send me the full call? I can test on my end

**Comment by dillonma** [comment]
Hi @Quantitative72. We modified some of the arguments because we added several other different geographies besides just tract aggregation. 

`tract = TRUE` should now be `agg_geo = "tract"`

See the vignette for other geographies: https://github.com/jamgreen/lehdr/blob/master/vignettes/getting_started.Rmd

**Comment by jamgreen** [comment]
Because @dillonma found the problem and offered additional info through the vignette I'm going to close this issue. Please let us know if you run into any additional problems.
